name: JD Build

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - '.github/workflows/JD-Build.yml'

  schedule:
    - cron: 0 */6 * * *

jobs:
  rsshub:
    runs-on: ubuntu-latest
    name: JD-Base Build
    steps:
      - name: Clone
        run: |
          git clone --depth 1 --single-branch https://github.com/dockere/jd-base jd
          find ./jd -type f -exec sed -i -e 's/https:\/\/gitee\.com\/dockere\/jd-base/https:\/\/github\.com\/dockere\/jd-base/g' {} \;
          find ./jd -type f -exec sed -i -e 's/https:\/\/gitee\.com\/lxk0301\/jd_docker/https:\/\/github\.com\/Apocalypsor\/jd_docker/g' {} \;
          find ./jd -type f -exec sed -i -e 's/git@gitee\.com:lxk0301\/jd_scripts\.git/https:\/\/github\.com\/zero205\/JD/g' {} \;
          find ./jd -type f -exec sed -i -e 's/https:\/\/registry\.npm\.taobao\.org/https:\/\/registry\.npmjs\.org\//g' {} \;

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Girhub Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REPO_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./jd
          file: ./jd/docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/apocalypsor/jd:latest
