name: JD Build

on:
  workflow_dispatch:

  schedule:
    - cron: 0 */6 * * *

jobs:
  rsshub:
    runs-on: ubuntu-latest
    name: JD-Base Build
    steps:
      - name: Clone
        run: |
          git clone --depth 1 --single-branch https://github.com/DovFork/jd-base jd
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Girhub Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REPO_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./jd
          file: ./jd/docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/apocalypsor/jd:latest
