name: JD Share Codes

on:
  workflow_dispatch:
  
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/JD-ShareCodes.yml'

  schedule:
    - cron: 5,35 2,10,18 1,2,10,11,20,21 * *

jobs:
  sharecodes:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade requests
      - name: Apply
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHATID: ${{ secrets.TG_CHATID }}
        run: |
          python JD-ShareCodes.py
          
