name: Rclone Dedupe

on:
  schedule:
    - cron: 0 */6 * * *

jobs:
  bolan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: rclone dedupe
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
      with:
        args: "dedupe bolan: --dedupe-mode largest -v --fast-list "
    - name: rclone cleanup
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
      with:
        args: "cleanup bolan: "
    - name: rclone rmdirs
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
      with:
        args: "rmdirs bolan: -v --fast-list "

  wuxian:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: rclone dedupe
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
      with:
        args: "dedupe wuxian:Storage --dedupe-mode largest -v --fast-list "
    - name: rclone cleanup
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
      with:
        args: "cleanup wuxian: "
    - name: rclone rmdirs
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
      with:
        args: "rmdirs wuxian:Storage -v --fast-list "
