name: Repo Sync

on:
  workflow_dispatch:
  
  push:
    branches:    
      - 'master'
    paths:
      - '.github/workflows/Repo-Sync.yaml'

  schedule:
    - cron: 53 * * * *

jobs:
  ariang:
    runs-on: ubuntu-latest
    env:
      project: Ariang
      DATABASE: ${{ secrets.DATABASE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: python -m pip install --upgrade pymongo dnspython
      - name: Check Upstream
        id: ariang
        run: |
          VER=$(curl -s -N https://api.github.com/repos/mayswind/AriaNg/releases | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | head -n 1)
          result=$(python Vercel/check.py $project $VER)
          [[ $result ]] && echo "VER=$VER" >> $GITHUB_ENV || true
          [[ $result ]] && curl -sSL https://apix.vercel.app/github/mayswind/AriaNg/AriaNg -o /tmp/tmp.zip && unzip -n /tmp/tmp.zip -d ./AriaNg || echo "Download failed!"
          [[ $result ]] && echo "::set-output name=status::proceed" || echo "Updated!"
      - name: Github ➡ FTP
        if: steps.ariang.outputs.status == 'proceed'
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./AriaNg/
          server-dir: /ariang.dov.moe/
      - name: Update
        if: steps.ariang.outputs.status == 'proceed'
        run: python Vercel/update.py $project ${{ env.VER }}

  microsoft-365-admin:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep Random Time
        run: sleep $(shuf -i 10-60 -n 1)
      - uses: actions/checkout@v2
      - name: Github ➡ Github
        id: microsoft-365-admin-update
        run: |
          RUNNER_DIR=`pwd`
          sed -i "s/rm -rf \/tmp\/dest_repo/rm -rf/g" Scripts/sync.sh
          bash Scripts/sync.sh \
            https://github.com/6mb/Microsoft-365-Admin master \
            https://${{ github.repository_owner }}:${{ secrets.REPO_TOKEN }}@github.com/DovFork/Microsoft-365-Admin
          cat /tmp/update > /dev/null && mv /tmp/dest_repo $RUNNER_DIR || echo "::set-output name=status::updated"
      - name: Set up Docker Buildx
        if: steps.microsoft-365-admin-update.outputs.status != 'updated'
        uses: docker/setup-buildx-action@v1
      - name: Github Docker Login
        if: steps.microsoft-365-admin-update.outputs.status != 'updated'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: dovfork
          password: ${{ secrets.REPO_TOKEN }}
      - name: Build and push
        if: steps.microsoft-365-admin-update.outputs.status != 'updated'
        uses: docker/build-push-action@v2
        with:
          context: ./dest_repo
          file: ./dest_repo/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/dovfork/microsoft-365-admin:latest

  jd-panel:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep Random Time
        run: sleep $(shuf -i 10-60 -n 1)
      - uses: actions/checkout@v2
      - name: Github ➡ Github
        id: jd-panel-update
        run: |
          RUNNER_DIR=`pwd`
          sed -i "s/rm -rf \/tmp\/dest_repo/rm -rf/g" Scripts/sync.sh
          bash Scripts/sync.sh \
            https://github.com/whyour/qinglong master \
            https://${{ github.repository_owner }}:${{ secrets.REPO_TOKEN }}@github.com/DovFork/jd-panel
          cat /tmp/update > /dev/null && mv /tmp/dest_repo $RUNNER_DIR || echo "::set-output name=status::updated"
      - name: Set up Docker Buildx
        if: steps.jd-panel-update.outputs.status != 'updated'
        uses: docker/setup-buildx-action@v1
      - name: Github Docker Login
        if: steps.jd-panel-update.outputs.status != 'updated'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: dovfork
          password: ${{ secrets.REPO_TOKEN }}
      - name: Build and push
        if: steps.jd-panel-update.outputs.status != 'updated'
        uses: docker/build-push-action@v2
        with:
          context: ./dest_repo
          file: ./dest_repo/docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/dovfork/jd-panel:latest

  jd-cookie:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep Random Time
        run: sleep $(shuf -i 10-60 -n 1)
      - uses: actions/checkout@v2
      - name: Github ➡ Github
        id: jd-cookie-update
        run: |
          RUNNER_DIR=`pwd`
          sed -i "s/rm -rf \/tmp\/dest_repo/rm -rf/g" Scripts/sync.sh
          bash Scripts/sync.sh \
            https://github.com/scjtqs/jd_cookie master \
            https://${{ github.repository_owner }}:${{ secrets.REPO_TOKEN }}@github.com/DovFork/JD-Coookie
          cat /tmp/update > /dev/null && mv /tmp/dest_repo $RUNNER_DIR || echo "::set-output name=status::updated"
      - name: Set up Docker Buildx
        if: steps.jd-cookie-update.outputs.status != 'updated'
        uses: docker/setup-buildx-action@v1
      - name: Github Docker Login
        if: steps.jd-cookie-update.outputs.status != 'updated'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: dovfork
          password: ${{ secrets.REPO_TOKEN }}
      - name: Build and push
        if: steps.jd-cookie-update.outputs.status != 'updated'
        uses: docker/build-push-action@v2
        with:
          context: ./dest_repo
          file: ./dest_repo/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/dovfork/jd-cookie:latest

  jd-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep Random Time
        run: sleep $(shuf -i 10-60 -n 1)
      - uses: actions/checkout@v2
      - name: Bot
        run: |
          bash Scripts/sync.sh \
            https://github.com/SuMaiKaDe/bot main \
            https://${{ github.repository_owner }}:${{ secrets.REPO_TOKEN }}@github.com/DovFork/jd-bot
      - name: JDHelloWorld
        run: |
          bash Scripts/sync.sh \
            https://github.com/JDHelloWorld/jd_scripts main \
            https://${{ github.repository_owner }}:${{ secrets.REPO_TOKEN }}@github.com/DovFork/jd-scripts
      - name: hundun
        run: |
          bash Scripts/sync.sh \
            https://github.com/whyour/hundun master \
            https://${{ github.repository_owner }}:${{ secrets.REPO_TOKEN }}@github.com/DovFork/hundun
      - name: ZCY01
        run: |
          bash Scripts/sync.sh \
            https://github.com/ZCY01/daily_scripts main \
            https://${{ github.repository_owner }}:${{ secrets.REPO_TOKEN }}@github.com/DovFork/ZCY01
      - name: yangtingxiao
        run: |
          bash Scripts/sync.sh \
            https://github.com/yangtingxiao/QuantumultX master \
            https://${{ github.repository_owner }}:${{ secrets.REPO_TOKEN }}@github.com/DovFork/yangtingxiao
      - name: JDDJ
        run: |
          bash Scripts/sync.sh \
            https://github.com/passerby-b/JDDJ main \
            https://${{ github.repository_owner }}:${{ secrets.REPO_TOKEN }}@github.com/DovFork/JDDJ
      - name: longzhuzhu
        run: |
          bash Scripts/sync.sh \
            https://github.com/longzhuzhu/nianyu main \
            https://${{ github.repository_owner }}:${{ secrets.REPO_TOKEN }}@github.com/DovFork/longzhuzhu
      - name: Ariszy
        run: |
          bash Scripts/sync.sh \
            https://github.com/Ariszy/Private-Script master \
            https://${{ github.repository_owner }}:${{ secrets.REPO_TOKEN }}@github.com/DovFork/Ariszy
      - name: moposmall
        run: |
          bash Scripts/sync.sh \
            https://github.com/moposmall/Script main \
            https://${{ github.repository_owner }}:${{ secrets.REPO_TOKEN }}@github.com/DovFork/moposmall
      - name: pxylen
        run: |
          bash Scripts/sync.sh \
            https://github.com/pxylen/dog_jd master \
            https://${{ github.repository_owner }}:${{ secrets.REPO_TOKEN }}@github.com/DovFork/pxylen
      - name: ztxtop
        run: |
          bash Scripts/sync.sh \
            https://github.com/ztxtop/x main \
            https://${{ github.repository_owner }}:${{ secrets.REPO_TOKEN }}@github.com/DovFork/ztxtop
      - name: airacg
        run: |
          bash Scripts/sync.sh \
            https://github.com/airacg/jd_task main \
            https://${{ github.repository_owner }}:${{ secrets.REPO_TOKEN }}@github.com/DovFork/airacg
      - name: JD_Diy
        run: |
          bash Scripts/sync.sh \
            https://github.com/chiupam/JD_Diy master \
            https://${{ github.repository_owner }}:${{ secrets.REPO_TOKEN }}@github.com/DovFork/JD-Diy
      - name: Sunert
        run: |
          bash Scripts/sync.sh \
            https://github.com/Sunert/Script master \
            https://${{ github.repository_owner }}:${{ secrets.REPO_TOKEN }}@github.com/DovFork/Sunert
      - name: curtinlv
        run: |
          bash Scripts/sync.sh \
            https://github.com/curtinlv/JD-Script main \
            https://${{ github.repository_owner }}:${{ secrets.REPO_TOKEN }}@github.com/DovFork/curtinlv
