name: Youtube Music

on:
  workflow_dispatch:
  
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/YTMusic.yml'

  schedule:
    - cron: 0 */3 * * *

jobs:
  ytmusic-merge:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ytmusicapi
      - name: Merge
        env:
          YT_PLAYLIST: ${{ secrets.YT_PLAYLIST }}
          YT_AUTH: ${{ secrets.YT_AUTH }}
        run: |
          echo $YT_AUTH > auth.json && python YTMusic-Merge.py
          